# Generated by Django 5.2.6 on 2025-09-10 13:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="اسم السنة الدراسية"),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                ("end_date", models.DateField(verbose_name="تاريخ النهاية")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="السنة الحالية"),
                ),
            ],
            options={
                "verbose_name": "السنة الدراسية",
                "verbose_name_plural": "السنوات الدراسية",
            },
        ),
        migrations.CreateModel(
            name="ExamType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="نوع الاختبار")),
                (
                    "weight_percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="الوزن النسبي"
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="الدرجة العظمى",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوع الاختبار",
                "verbose_name_plural": "أنواع الاختبارات",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="اسم الصف")),
                ("level", models.IntegerField(verbose_name="مستوى الصف")),
                ("description", models.TextField(blank=True, verbose_name="وصف الصف")),
            ],
            options={
                "verbose_name": "الصف الدراسي",
                "verbose_name_plural": "الصفوف الدراسية",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="اسم المدرسة")),
                ("address", models.TextField(verbose_name="العنوان")),
                ("phone", models.CharField(max_length=20, verbose_name="رقم الهاتف")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                (
                    "principal_name",
                    models.CharField(max_length=100, verbose_name="اسم المدير"),
                ),
                (
                    "logo",
                    models.URLField(blank=True, null=True, verbose_name="شعار المدرسة"),
                ),
            ],
            options={
                "verbose_name": "المدرسة",
                "verbose_name_plural": "المدارس",
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="اسم الفصل")),
                ("capacity", models.IntegerField(default=30, verbose_name="سعة الفصل")),
                (
                    "classroom_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الفصل"
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.academicyear",
                        verbose_name="السنة الدراسية",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.grade",
                        verbose_name="الصف",
                    ),
                ),
            ],
            options={
                "verbose_name": "الفصل",
                "verbose_name_plural": "الفصول",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم الطالب"
                    ),
                ),
                ("enrollment_date", models.DateField(verbose_name="تاريخ التسجيل")),
                (
                    "guardian_name",
                    models.CharField(max_length=100, verbose_name="اسم ولي الأمر"),
                ),
                (
                    "guardian_phone",
                    models.CharField(max_length=20, verbose_name="هاتف ولي الأمر"),
                ),
                (
                    "guardian_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="بريد ولي الأمر"
                    ),
                ),
                (
                    "guardian_relationship",
                    models.CharField(
                        default="الوالد", max_length=50, verbose_name="صلة القرابة"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(max_length=100, verbose_name="جهة الاتصال الطارئ"),
                ),
                (
                    "emergency_phone",
                    models.CharField(max_length=20, verbose_name="هاتف الطوارئ"),
                ),
                (
                    "medical_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات طبية"),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schoolclass",
                        verbose_name="الفصل",
                    ),
                ),
            ],
            options={
                "verbose_name": "الطالب",
                "verbose_name_plural": "الطلاب",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="اسم المادة")),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="رمز المادة"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف المادة"),
                ),
                (
                    "credit_hours",
                    models.IntegerField(default=3, verbose_name="عدد الساعات"),
                ),
                (
                    "grades",
                    models.ManyToManyField(
                        to="core.grade", verbose_name="الصفوف المطبقة"
                    ),
                ),
            ],
            options={
                "verbose_name": "المادة",
                "verbose_name_plural": "المواد",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="الرقم الوظيفي"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(max_length=100, verbose_name="التخصص"),
                ),
                (
                    "qualification",
                    models.CharField(max_length=100, verbose_name="المؤهل"),
                ),
                (
                    "experience_years",
                    models.IntegerField(default=0, verbose_name="سنوات الخبرة"),
                ),
                ("hire_date", models.DateField(verbose_name="تاريخ التوظيف")),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="الراتب"
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True,
                        to="core.schoolclass",
                        verbose_name="الفصول المُدرَّسة",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        to="core.subject", verbose_name="المواد المُدرَّسة"
                    ),
                ),
            ],
            options={
                "verbose_name": "المدرس",
                "verbose_name_plural": "المدرسون",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="عنوان الدرس")),
                ("description", models.TextField(verbose_name="وصف الدرس")),
                ("file_url", models.URLField(verbose_name="رابط الملف")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("ppt", "PowerPoint"),
                            ("doc", "Word"),
                            ("video", "فيديو"),
                            ("link", "رابط خارجي"),
                        ],
                        max_length=20,
                        verbose_name="نوع الملف",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="حجم الملف"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منشور"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ النشر"),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        to="core.schoolclass", verbose_name="الفصول المستهدفة"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subject",
                        verbose_name="المادة",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.teacher",
                        verbose_name="المدرس",
                    ),
                ),
            ],
            options={
                "verbose_name": "الدرس",
                "verbose_name_plural": "الدروس",
                "ordering": ["-publish_date"],
            },
        ),
        migrations.CreateModel(
            name="Grade_Score",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="الدرجة",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="الدرجة العظمى",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="النسبة المئوية"
                    ),
                ),
                (
                    "grade_letter",
                    models.CharField(
                        choices=[
                            ("A+", "ممتاز مرتفع"),
                            ("A", "ممتاز"),
                            ("B+", "جيد جداً مرتفع"),
                            ("B", "جيد جداً"),
                            ("C+", "جيد مرتفع"),
                            ("C", "جيد"),
                            ("D", "مقبول"),
                            ("F", "راسب"),
                        ],
                        max_length=2,
                        verbose_name="التقدير",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("exam_date", models.DateField(verbose_name="تاريخ الاختبار")),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.academicyear",
                        verbose_name="السنة الدراسية",
                    ),
                ),
                (
                    "exam_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.examtype",
                        verbose_name="نوع الاختبار",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.student",
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subject",
                        verbose_name="المادة",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.teacher",
                        verbose_name="المدرس",
                    ),
                ),
            ],
            options={
                "verbose_name": "الدرجة",
                "verbose_name_plural": "الدرجات",
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان الإعلان"),
                ),
                ("content", models.TextField(verbose_name="محتوى الإعلان")),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("general", "عام"),
                            ("exam", "اختبار"),
                            ("homework", "واجب"),
                            ("holiday", "إجازة"),
                            ("important", "مهم"),
                            ("urgent", "عاجل"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="نوع الإعلان",
                    ),
                ),
                (
                    "target_all_school",
                    models.BooleanField(default=False, verbose_name="جميع المدرسة"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منشور"),
                ),
                ("is_urgent", models.BooleanField(default=False, verbose_name="عاجل")),
                (
                    "publish_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ النشر"),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ انتهاء الصلاحية"
                    ),
                ),
                (
                    "target_classes",
                    models.ManyToManyField(
                        blank=True,
                        to="core.schoolclass",
                        verbose_name="الفصول المستهدفة",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.teacher",
                        verbose_name="المؤلف",
                    ),
                ),
            ],
            options={
                "verbose_name": "الإعلان",
                "verbose_name_plural": "الإعلانات",
                "ordering": ["-publish_date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "arabic_first_name",
                    models.CharField(
                        max_length=50, verbose_name="الاسم الأول بالعربية"
                    ),
                ),
                (
                    "arabic_last_name",
                    models.CharField(
                        max_length=50, verbose_name="اسم العائلة بالعربية"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم الهوية"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="رقم الهاتف")),
                ("address", models.TextField(verbose_name="العنوان")),
                ("date_of_birth", models.DateField(verbose_name="تاريخ الميلاد")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "ذكر"), ("female", "أنثى")],
                        max_length=10,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "مدير"),
                            ("teacher", "مدرس"),
                            ("student", "طالب"),
                        ],
                        max_length=20,
                        verbose_name="الدور",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "profile_picture",
                    models.URLField(
                        blank=True, null=True, verbose_name="صورة الملف الشخصي"
                    ),
                ),
                (
                    "supabase_user_id",
                    models.UUIDField(unique=True, verbose_name="معرف Supabase"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "الملف الشخصي",
                "verbose_name_plural": "الملفات الشخصية",
            },
        ),
        migrations.AddField(
            model_name="teacher",
            name="user_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.userprofile",
                verbose_name="الملف الشخصي",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.userprofile",
                verbose_name="الملف الشخصي",
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان التقرير"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("attendance", "الحضور"),
                            ("grades", "الدرجات"),
                            ("students", "الطلاب"),
                            ("teachers", "المدرسين"),
                            ("financial", "مالي"),
                            ("general", "عام"),
                        ],
                        max_length=20,
                        verbose_name="نوع التقرير",
                    ),
                ),
                (
                    "date_from",
                    models.DateField(blank=True, null=True, verbose_name="من تاريخ"),
                ),
                (
                    "date_to",
                    models.DateField(blank=True, null=True, verbose_name="إلى تاريخ"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المعالجة"),
                            ("completed", "مكتمل"),
                            ("failed", "فشل"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط الملف"),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        default="pdf",
                        max_length=10,
                        verbose_name="تنسيق الملف",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.academicyear",
                        verbose_name="السنة الدراسية",
                    ),
                ),
                (
                    "school_classes",
                    models.ManyToManyField(
                        blank=True, to="core.schoolclass", verbose_name="الفصول"
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True, to="core.subject", verbose_name="المواد"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                        verbose_name="مُنشئ التقرير",
                    ),
                ),
            ],
            options={
                "verbose_name": "التقرير",
                "verbose_name_plural": "التقارير",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("sunday", "الأحد"),
                            ("monday", "الاثنين"),
                            ("tuesday", "الثلاثاء"),
                            ("wednesday", "الأربعاء"),
                            ("thursday", "الخميس"),
                        ],
                        max_length=10,
                        verbose_name="يوم الأسبوع",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="وقت البداية")),
                ("end_time", models.TimeField(verbose_name="وقت النهاية")),
                (
                    "classroom",
                    models.CharField(max_length=20, verbose_name="رقم الفصل"),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schoolclass",
                        verbose_name="الفصل",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subject",
                        verbose_name="المادة",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.teacher",
                        verbose_name="المدرس",
                    ),
                ),
            ],
            options={
                "verbose_name": "الجدول",
                "verbose_name_plural": "الجداول",
                "unique_together": {("school_class", "day_of_week", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="التاريخ")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "حاضر"),
                            ("absent", "غائب"),
                            ("late", "متأخر"),
                            ("excused", "غياب بعذر"),
                        ],
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "recorded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت التسجيل"),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.schoolclass",
                        verbose_name="الفصل",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.student",
                        verbose_name="الطالب",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.subject",
                        verbose_name="المادة",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.teacher",
                        verbose_name="المدرس",
                    ),
                ),
            ],
            options={
                "verbose_name": "الحضور",
                "verbose_name_plural": "سجلات الحضور",
                "unique_together": {("student", "date", "subject")},
            },
        ),
    ]
