# Generated by Django 5.2.6 on 2025-09-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='supabase_user_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='معرف Supabase (اختياري)'),
        ),
    ]
